
package de.jworks.fpp.labs.indesign.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicePortType", targetNamespace = "http://localhost:80/Service.wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePortType {


    /**
     * Service definition of function IDSP__RunScript
     * 
     * @param scriptResult
     * @param errorNumber
     * @param runScriptParameters
     * @param errorString
     */
    @WebMethod(operationName = "RunScript")
    @RequestWrapper(localName = "RunScript", targetNamespace = "http://ns.adobe.com/InDesign/soap/", className = "de.jworks.fpp.labs.indesign.soap.RunScript")
    @ResponseWrapper(localName = "RunScriptResponse", targetNamespace = "http://ns.adobe.com/InDesign/soap/", className = "de.jworks.fpp.labs.indesign.soap.RunScriptResponse")
    public void runScript(
        @WebParam(name = "runScriptParameters", targetNamespace = "")
        RunScriptParameters runScriptParameters,
        @WebParam(name = "errorNumber", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> errorNumber,
        @WebParam(name = "errorString", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> errorString,
        @WebParam(name = "scriptResult", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Data> scriptResult);

    /**
     * Service definition of function IDSP__BeginSession
     * 
     * @return
     *     returns long
     */
    @WebMethod(operationName = "BeginSession")
    @WebResult(name = "sessionID", targetNamespace = "")
    @RequestWrapper(localName = "BeginSession", targetNamespace = "http://ns.adobe.com/InDesign/soap/", className = "de.jworks.fpp.labs.indesign.soap.BeginSession")
    @ResponseWrapper(localName = "BeginSessionResponse", targetNamespace = "http://ns.adobe.com/InDesign/soap/", className = "de.jworks.fpp.labs.indesign.soap.BeginSessionResponse")
    public long beginSession();

    /**
     * Service definition of function IDSP__EndSession
     * 
     * @param sessionID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "EndSession")
    @WebResult(name = "errorCode", targetNamespace = "")
    @RequestWrapper(localName = "EndSession", targetNamespace = "http://ns.adobe.com/InDesign/soap/", className = "de.jworks.fpp.labs.indesign.soap.EndSession")
    @ResponseWrapper(localName = "Result", targetNamespace = "http://ns.adobe.com/InDesign/soap/", className = "de.jworks.fpp.labs.indesign.soap.Result")
    public int endSession(
        @WebParam(name = "sessionID", targetNamespace = "")
        long sessionID);

}
